baseurl = "/"
canonifyURLs = true
disqusShortname = "shortname"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
paginate = "3"
pluralizeListTitles = false
preserveTaxonomyNames = true
title = "Dylannum"
[[menu.main]]
identifier = "fa fa-home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "fa fa-id-card-o"
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
identifier = "fa fa-list"
name = "Itemized"
url = "/itemized/"
weight = 4
[[menu.main]]
identifier = "fa fa-sitemap"
name = "Categories"
url = "/categories/"
weight = 5
[[menu.main]]
identifier = "fa fa-envelope-o"
name = "Contact"
url = "/contact/"
weight = 6
[params]
MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"
categoriesByCount = true
customCSS = ["default"]
customJS = ["default"]
description = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
disable_highlight = false
dynamicTitles = true
faviconVersion = ""
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "css"]
highlightjsTheme = "github"
highlightjsVersion = "9.11.0"
includeReadingTime = true
loadFavicon = false
navbarTitle = "Future Imperfect"
rssAppearAtBottom = true
rssAppearAtTop = true
showSidebarCategories = true
socialAppearAtBottom = true
socialAppearAtTop = true
socialShare = true
socialShareEmail = true
socialShareFacebook = true
socialShareGoogleplus = true
socialShareLinkedin = true
socialSharePinterest = true
socialShareReddit = true
socialShareStumbleupon = true
socialShareTwitter = true
viewMorePostLink = "/blog/"
[params.intro]
about = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."
header = "Dylannum !"
paragraph = "Another fine responsive site template by <a href=\"http://html5up.net\">HTML5 UP</a>. Ported by Julio Pescador with some extra goodies <i class='fa fa-hand-peace-o'></i>"
[params.intro.pic]
alt = "Hugo Future Imperfect"
circle = true
imperfect = true
src = "https://www.pexels.com/photo/woman-covering-her-two-eyes-704977/"
width = ""
[params.postAmount]
sidebar = 5
[params.staticman]
branch = ""
repo = ""
staticman = false
username = ""
[params.staticman.recaptcha]
secret = "ENCRYPTED_SECRET"
sitekey = "SITE_KEY"
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
email = "example"
facebook = "example"
flickr = "example"
foursquare = ""
github = "jpescador/hugo-future-imperfect"
gitlab = ""
googleplus = ""
googlescholar = ""
instagram = "example"
jsfiddle = ""
linkedin = "example"
linkedin_company = "examplebusiness"
medium = ""
orcid = ""
pinterest = "example"
qq = ""
quora = ""
reddit = "example"
researchgate = "example"
skype = ""
slideshare = ""
snapchat = ""
stackoverflow = ""
telegram = "example"
tumblr = ""
twitter = "example"
vimeo = ""
vine = ""
wechat = ""
whatsapp = ""
wordpress = ""
xing = ""
youtube = ""
